version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12.3
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-52-204-232-46.compute-1.amazonaws.com
            port: '5432'
            database: d16iolgacum086
            ssl: true
            user: qgtwpudeqqlked
            password: a7e45bd610e37cfa74ae18ddad1add52340f3758ba6104782f7d0f4aac823b67
            migrations: true